bskysim = "../bskysim/zig-out/bin/bskysim"
construct_cascade = "../construct-cascades/zig-out/bin/construct-cascade"
dataset_creation = "../dataset-creation/dataset-creation"

data = "../bskysim/data/10K_monotonous.bin"
runs = 16
workers = 4

traces_dir = "traces"
cascades_dir = "cascades"
datasets_dir = "datasets"
buckets = 256
temp_dir = "/tmp/cascade-building"

[[configs]]
name = "final"
path = "../bskysim/simconfs/final.json"

[[configs]]
name = "all1"
path = "../bskysim/simconfs/all1.json"
